@baseUrl = http://localhost:5000

@urlPath = api/v1

###

POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "fikre",
  "password": "123456",
  "email": "fikre@gmail.com",
  "avatarColor": "red",
  "avatarImage": "https://assets.vogue.com/photos/5876fe0a8a28e998768824d3/4:3/w_795,h_597,c_limit/david-gandy.jpg"
}

###

POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "eldad",
  "password": "123456"
}

###

GET {{baseUrl}}/{{urlPath}}/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true

###

GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "eldadf456@gmail.com"
}

###
POST {{baseUrl}}/{{urlPath}}/reset-password/603b92b2d29811a9d29d2f3226e55e26982d2922
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "password": "1234567",
  "confirmPassword": "1234567"
}


