@baseUrl = http://localhost:5000
@urlPath = api/v1

###

PUT {{baseUrl}}/{{urlPath}}/user/follow/67deb6ede8799971368824d5
Content-Type: application/json
Accept: application/json
withCredentials: true

{}


###

PUT {{baseUrl}}/{{urlPath}}/user/unfollow/67d18ce26b319beeb077f36d/67d18d316b319beeb077f381
Content-Type: application/json
Accept: application/json
withCredentials: true

{}


###

GET {{baseUrl}}/{{urlPath}}/user/following
Content-Type: application/json
Accept: application/json
withCredentials: true

{}


###

GET {{baseUrl}}/{{urlPath}}/user/followers/67bc589111945b4bf432d7a8
Content-Type: application/json
Accept: application/json
withCredentials: true


###

PUT {{baseUrl}}/{{urlPath}}/user/block/67bc588611945b4bf432d7a1
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

