@baseUrl = http://localhost:5000
@urlPath = api/v1

###

POST {{baseUrl}}/{{urlPath}}/images/profile
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "image": "https://upload.wikimedia.org/wikipedia/commons/6/6e/Kylie_Jenner1_%28cropped%29.png"
}


###

POST {{baseUrl}}/{{urlPath}}/images/background
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "image": "https://res.cloudinary.com/dggixttgq/image/upload/v1742658563/avu2kanmqw9x0ogjsyvw.jpg"
}



###

DELETE {{baseUrl}}/{{urlPath}}/images/
Content-Type: application/json
Accept: application/json
withCredentials: true

###

DELETE {{baseUrl}}/{{urlPath}}/images/
Content-Type: application/json
Accept: application/json
withCredentials: true


###


GET {{baseUrl}}/{{urlPath}}/images/67dae4dd4a24251005859ad3
Content-Type: application/json
Accept: application/json
withCredentials: true






