@baseUrl = http://localhost:5000
@urlPath = api/v1

###

POST {{baseUrl}}/{{urlPath}}/images/profile
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "image": "https://static.wikia.nocookie.net/id4/images/6/61/D99E253B-203E-489A-937B-1A802EB41BB0.jpg/revision/latest?cb=20220102193014"
}


###

POST {{baseUrl}}/{{urlPath}}/images/background
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "image": "https://res.cloudinary.com/dggixttgq/image/upload/v1742485342/67dae4dd4a24251005859ad3"
}



###

DELETE {{baseUrl}}/{{urlPath}}/images/
Content-Type: application/json
Accept: application/json
withCredentials: true

###

DELETE {{baseUrl}}/{{urlPath}}/images/
Content-Type: application/json
Accept: application/json
withCredentials: true


###


GET {{baseUrl}}/{{urlPath}}/images/67dae4dd4a24251005859ad3
Content-Type: application/json
Accept: application/json
withCredentials: true






