@baseUrl = http://localhost:5000
@urlPath = api/v1

###

POST {{baseUrl}}/{{urlPath}}/images/profile
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "image": "https://media.licdn.com/dms/image/v2/D4E03AQFSJHY0JzUCug/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1730833758630?e=1746057600&v=beta&t=bOSwlFNSkdFkSmUHfzLFaALvpuB9aQQdpQ02S0jvzHY"
}


###

POST {{baseUrl}}/{{urlPath}}/images/background
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "image": "https://res.cloudinary.com/dggixttgq/image/upload/v1740590137/67be1c53ca10b4f2838ef1f5"
}


###

DELETE {{baseUrl}}/{{urlPath}}/images/
Content-Type: application/json
Accept: application/json
withCredentials: true

###

DELETE {{baseUrl}}/{{urlPath}}/images/67bf4f7af81bd408c39a9a03
Content-Type: application/json
Accept: application/json
withCredentials: true


###


GET {{baseUrl}}/{{urlPath}}/images/67bc589111945b4bf432d7a8
Content-Type: application/json
Accept: application/json
withCredentials: true






