@baseUrl = http://localhost:5000
@urlPath = api/v1


###

PUT {{baseUrl}}/{{urlPath}}/notification/67bc588611945b4bf432d7a1
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###

GET {{baseUrl}}/{{urlPath}}/notifications
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

