@baseUrl = http://localhost:5000
@urlPath = api/v1


###

GET {{baseUrl}}/{{urlPath}}/user/all/1
Content-Type: application/json
Accept: application/json
withCredentials: true



###


GET {{baseUrl}}/{{urlPath}}/user/profile/posts/eldad/67be1c53ca10b4f2838ef1f5/974143628422
Content-Type: application/json
Accept: application/json
withCredentials: true


###


GET {{baseUrl}}/{{urlPath}}/user/profile/users/suggestions
Content-Type: application/json
Accept: application/json
withCredentials: true
